/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/freemapTheme.ts
 * Command: astryx theme build theme/freemapTheme.ts
 * Generated: 2026-07-27T19:21:30.867Z
 */

/// <reference path="./freemap.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const freemapTheme: DefinedTheme;
