/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/freemapTheme.ts
 * Command: astryx theme build theme/freemapTheme.ts
 * Generated: 2026-07-27T19:21:30.865Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
